### PR TITLE
Add option to disable LCD wifi info page

### PR DESCRIPTION
**Pull request by sredni**
It is useful for public available sensors to not show wifi informations.

### CODE REVIEW

**Comment by dpvue** [comment]
yes, indeed! it would be helpful this feature for public sensors

**Comment by netmaniac** [comment]
Before I will merge this PR I need to check whole display code - something is wrong there. I'm looking right now on two sensors with LCD 16x2 and 20x4 and display on 16x2 need some work. Right now we are busy with our regular operations in Nettigo, so it will take two or three, but PR will be merged.

**Comment by sredni** [comment]
Oh that’s probably my bad, I have no 16x2 LCD to test. I will look at it later today and try to fix it.

**Comment by sredni** [comment]
@netmaniac someone missed the HECA info on 1602 LCD which caused incorrect page count, should be fixed now.

**Comment by netmaniac** [comment]
Sorry for delay. There was code fixed already based on Your first commit, and I have just pushed my code. It fixes problem with both displays and introduces enum to avoid such mistakes in future. Code is in master, in one or two hours I plan do release of new version of binaries.

**Comment by netmaniac** [comment]
Function implemented.

**Comment by netmaniac** [comment]
New release 2020-28 on update server. @sredni thank You for contributing.

**Pull request closed without merging**
